import fs from 'node:fs';
import path from 'node:path';

const rootDir = path.resolve(import.meta.dirname, '..');
const envPath = path.join(rootDir, '.env');
const outputPath = path.join(rootDir, 'WatchGPT', 'Config', 'LocalSecrets.xcconfig');

const fileEnv = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};
const apiKey = process.env.OPENAI_API_KEY ?? fileEnv.OPENAI_API_KEY ?? '';

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(
  outputPath,
  [
    '// Generated by npm run configure:watch. Do not commit this file.',
    `WATCHGPT_OPENAI_API_KEY = ${apiKey}`,
    '',
  ].join('\n'),
);

console.log(
  apiKey
    ? 'Baked OpenAI API key into the local debug build.'
    : 'No OPENAI_API_KEY found; the Watch app will start without a key (set one in Settings or rerun with OPENAI_API_KEY=...).',
);

function parseEnv(text) {
  const env = {};

  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const equalsAt = trimmed.indexOf('=');

    if (equalsAt === -1) {
      continue;
    }

    const key = trimmed.slice(0, equalsAt).trim();
    let value = trimmed.slice(equalsAt + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}
